### ISSUE TITLE
Doesn't work on Twitter

### ISSUE THREAD

**Issue by jehrr** [2captcha/2captcha-solver#17]
Latest version 3.1.0 doesn't detect funcaptcha on twitter.com:
https://help.twitter.com/en/forms/safety-and-sensitive-content/cse

We can see this error in console upon opening the form:
![Screenshot_20221003_130145](https://user-images.githubusercontent.com/79864894/193563815-0af2d6a7-d02f-4874-8d9d-21817220e393.png)

![スクリーンショット 2022-10-03 17 17 54](https://user-images.githubusercontent.com/79864894/193561051-dbac6515-29dc-43a4-97e7-53edb7fd4432.jpg)
![スクリーンショット 2022-10-03 17 17 51](https://user-images.githubusercontent.com/79864894/193561058-c4e1df16-1ad4-4ef1-903f-e66b16964d4c.jpg)

**Comment by 2captcha** [comment]
Looks like it was broken in the latest update.

**Comment by 2captcha** [comment]
Fixed in v3.1.1, on moderation in Web Store.
