### ISSUE TITLE
Actual use demand

### ISSUE THREAD

**Issue by 760644586** [2captcha/2captcha-solver#22]
1. Chrome kernel. Version 87

2. The arkoselabs verification needs to be cracked

3. How to modify the file so that the plug-in can use the API key automatically

4. How to modify the file to make the plug-in default API key

5. How to modify the file to enable the arkoselabs switch of the plug-in

6. I can't change the Chrome kernel version

7. I cannot manually configure the API key

8. I cannot log in to the API key manually

9. I cannot manually set the switch of arkoselabs to ON

10. I need to change the API key by modifying the file, and then the plug-in can work automatically

11. Manual configuration is not allowed

**Comment by 760644586** [comment]
Please give me some advice

**Comment by 760644586** [comment]
I have software used by many users, but now arkoselabs need to be cracked, but I can't let users manually configure 2captcha

**Comment by 2captcha** [comment]
Just modify [config.js](https://github.com/2captcha/2captcha-solver/blob/main/common/config.js) setting the `apiKey` to your API key and `autoSolveArkoselabs` to `true`.
