### ISSUE TITLE
[Bug]: Enable plugin switch does't work as expected

### ISSUE THREAD

**Issue by alwagnerjr** [2captcha/2captcha-solver#24]
The `Enable plugin` switch in the popup does not prevent the extension from intercepting the captcha.
The interceptor/hunters scripts should check if the plugin state is `enabled` before intercepting the captchas.

**Comment by 2captcha** [comment]
Splitted this case into:
- #25 
- #26 

And I'll leave this one as a bug report of incorrect switch button logic.
