### ISSUE TITLE
Extension doesn't work with normal captcha on Yandex

### ISSUE THREAD

**Issue by alwagnerjr** [2captcha/2captcha-solver#33]
The error ERROR_ZERO_CAPTCHA_FILESIZE. When using "Solve automatically" mode, button "Solve captcha" is not displayed at all after clicking on field for answer and choosing "Put captcha answer here" . 
Page: https://market.yandex.ru/showcaptcha?mt=78493817442B7C27C00B765FA4F0EB04150F08AE157F743DAD1EC2BF9200F1233D83&retpath=aHR0cHM6Ly9tYXJrZXQueWFuZGV4LnJ1L2NhdGFsb2ctLXVtbnllLWNoYXN5LWktYnJhc2xldHkvMjY4OTM4MzAvbGlzdD9oaWQ9MTA0OTgwMjU%2C_f226239745db949370a938e7d91cee19&t=3/1673333841/024a4967a80c3ebcbe12c9636e91d2f4&u=d27623c1-1639ac08-42dd7f86-9269b601&s=38f77ccf8e97489b85e81defba98c084

**Comment by kratzky** [comment]
fixed in v3.3.2
