### ISSUE TITLE
ERROR_WRONG_GOOGLEKEY when solving on homedepot.com

### ISSUE THREAD

**Issue by jehrr** [2captcha/2captcha-solver#34]
The extension couldn't bypass captcha on homedepot.com
URL is https://www.homedepot.com/auth/view/createaccount/diy
For some reason there is no _googlekey_ in the request to in.php, screenshots attached.
![photo_2023-01-16_13-21-00](https://user-images.githubusercontent.com/79864894/212666988-905ba0c5-dd11-4455-81b4-2a1f2a344996.jpg)
![Screenshot_20230116_131708](https://user-images.githubusercontent.com/79864894/212666991-3140970b-699e-43b4-a586-39c5cfafce57.jpg)

**Comment by kratzky** [comment]
For some reason `getRecaptchaWidgetInfo` in [hunter.js](https://github.com/2captcha/2captcha-solver/blob/main/content/captcha/recaptcha/hunter.js) loses the value of `sitekey` before the info is returned.

**Comment by developer-vasily** [comment]
Need sample work URL

**Comment by kratzky** [comment]
At the moment there's only v3 at the page and this v3 is detected properly.
