### ISSUE TITLE
Extension doesn't work with reCaptcha captcha on mail.ru

### ISSUE THREAD

**Issue by alwagnerjr** [2captcha/2captcha-solver#40]
https://account.mail.ru/user/2-step-auth/passwords/add  captcha appears after entering password name and account password
<img width="2048" alt="Снимок экрана 2023-02-08 в 21 54 00" src="https://user-images.githubusercontent.com/68099709/217522704-9f5547e4-e85a-4bf6-a3a1-610982398e1f.png">

Solver bar doesn't appear on the page in both location mode. Captcha-widget element doesn't have any captcha's parameter data.

**Comment by developer-vasily** [comment]
Captcha button not displayed in page under button. Please use options "Button position: Bottom right corner"
