### ISSUE TITLE
question about hcaptcha invisible

### ISSUE THREAD

**Issue by dzmitry-duboyski** [2captcha/2captcha-solver#46]
Can the extension distinguish between an invisible hcaptcha and hcaptcha ?
When I submit hcaptcha invisible from the demo page https://2captcha.com/demo/hcaptcha-invisible, the extension does not specify the `invisible=1` parameter. But at the same time, hcaptcha invisible is successfully solved on the demo page using the extension.

The extension must specify the parameter `invisible=1` when sending hcaptcha invisible located at https://2captcha.com/demo/hcaptcha-invisible?

Screenshot:
![image](https://user-images.githubusercontent.com/38065632/224044175-62b44b6d-eb71-4d4d-8533-e2f4aa9822b7.png)

**Comment by kratzky** [comment]
Basically, there's no huge difference when the `invisible` flag is added, the API works the same way, so it's not a `MUST`.

**Comment by dzmitry-duboyski** [comment]
@kratzky thank you for your answer.
