### ISSUE TITLE
Extension blocks loading the captcha on page

### ISSUE THREAD

**Issue by alwagnerjr** [2captcha/2captcha-solver#51]
Enabled extension blocks loading the captcha on page. Problem occurs on some sites.

version: 3.3.3

Example: https://us02web.zoom.us/rec/component-page?action=viewdetailpage&sharelevel=meeting&useWhichPasswd=meeting&clusterId=us02&componentName=need-password&meetingId=VZEksBJ3EIsH0v5AcJNlgyP4mvKZejZW9YBrTb5bKYNAzndKF5pt35LG5G6sGxZX.uhJkNsOcVtaSag_1&originRequestUrl=https%3A%2F%2Fus02web.zoom.us%2Frec%2Fplay%2Fk_ZMMCZHjLDXuxMqxjGgUpZWCWzY_kk74qZjBzM24O34NnBKnWkP9IjeJGAAcCUVXskGBRgWbeJXU1ku.NHsMR4Uqwxy0DT0B%3FcanPlayFromShare%3Dtrue%26from%3Dshare_recording_detail%26continueMode%3Dtrue%26componentName%3Drec-play%26originRequestUrl%3Dhttps%253A%252F%252Fus02web.zoom.us%252Frec%252Fshare%252FA8_UYE2dgm3_4fpGW_jtZkoh8mmLbftdK8b7nkCDzSY6kkt7kzwFTVgA_g9XwIo1.9u0Fjzj_YruX72zC

Type of captcha: reCaptcha v2 Enterprise

How to trigger the captcha: enter the wrong(any, random) password several times on the site i specified earlier
Result: If the extension is enable, captcha doesn't load on the page. If you disable the extension and reload the page, captcha will load and then you may enable extension for bypassing.

**Comment by developer-vasily** [comment]
Need works sample page
