### ISSUE TITLE
Extension doesn't work with Cloudflare Turnstile on https://signin.infusionsoft.com/login

### ISSUE THREAD

**Issue by alwagnerjr** [2captcha/2captcha-solver#52]
https://signin.infusionsoft.com/login captcha appears after following a link

<img width="1470" alt="Снимок экрана 2023-04-08 в 00 33 19" src="https://user-images.githubusercontent.com/68099709/230626476-6d58ce15-bec5-4031-ab78-ff67fec36541.png">

Solver bar doesn't appear on the page in both location mode. Captcha-widget element doesn't have any captcha's parameter data.

Version: 3.3.3

**Comment by meotimdihia** [comment]
The element #cf-turnstile is not always existed. => The extension can't detect the turnstile on the age.

**Comment by oceanemil** [comment]
Similar issue on https://coinlist.co/login
There is name="cf-turnstile-response" and iframe with Cloudflare Turnstile challenge, however, 2Captcha can't find it and does not solve it.

**Comment by kratzky** [comment]
We need to intercept `pagedata` and `data` values on cloudflare security pages.
To do se we can redefine `turnstile.render` and grab the required parameters from the 2nd argument like:

```js
window.turnstile.render = (a, b) => {
  let p = {
    method: "turnstile",
    key: "{{key}}",
    sitekey: b.sitekey,
    pageurl: window.location.href,
    data: b.cData,
    pagedata: b.chlPageData,
    action: b.action,
    userAgent: navigator.userAgent,
    json: 1
  }
  console.log(JSON.stringify(p))
  window.tsCallback = b.callback
  return 'foo'
}
``` 

@developer-vasily could you please look into this?

**Comment by developer-vasily** [comment]
Duplicate #58

**Comment by developer-vasily** [comment]
Duplicate #58

**Comment by Pilaton** [comment]
@kratzky  The CF captcha currently has 0% recognition.

**Comment by kratzky** [comment]
> @kratzky The CF captcha currently has 0% recognition.

Yep, CF team do a great job, none of the methods for CF challenge works for more than a couple of days. I guess the support of CF challenge will be dropped soon.
