### ISSUE TITLE
Extension doesn't work correctly with normal captcha on Yandex

### ISSUE THREAD

**Issue by alwagnerjr** [2captcha/2captcha-solver#57]
Extension sends incorrect image from Yandex captcha page. 
It sends only first image correctly, then it sends previous captcha images and workers answer wrong.
<img width="1470" alt="Снимок экрана 2023-06-20 в 21 42 31" src="https://github.com/2captcha/2captcha-solver/assets/68099709/b765c1e4-3c6d-498d-af6c-dd3cc1778697">

Example page: 
https://yandex.com.tr/showcaptcha?mt=F525FAE742146AD1BC52BD485119B6218F102DA366573F91C2B6E538E9C07D39F359D82208F0F2F4680117A13C1C2A4E0E0E39E138F2411029C0253309F56119CCA2C4AE14C19FB72A4AD68B23D45894033E54E0CD57C87DCA61FC1E&retpath=aHR0cHM6Ly95YW5kZXguY29tLnRyL3NlYXJjaD90ZXh0PWdhZ2FnJTI3JmxyPTAmbXNpZD0xNjg2OTc4OTk2MTEyMTU2LTY4MjgzNzU5MTk5NDI1NTgzNjktYmFsYW5jZXItbDdsZXZlbGVyLWt1YnIteXAtc2FzLTk4LUJBTC03MzA5JnNlYXJjaF9zb3VyY2U9eWFjb20udHJfZGVza3RvcF9jb21tb24mc3VnZ2VzdF9yZXFpZD05NTY1MjQ0MzUxNjg2OTczNzM5ODc4MDUzNzY5MTMwNDQ%2C_e40103cbf0376344333b7faa0810e4cf&status=failed&t=3/1686978998/dfb6a59c91ecc511602c2ca3f436bb85&u=b6a961d6-d91cdf3b-98dd43b5-76ec04c0&s=1b514a9ada8ab6a9bf8b3bc3b8143d59

**Comment by developer-vasily** [comment]
Url doesn't work. Please update the example.

**Comment by kratzky** [comment]
There were some significant changes in Yandex captcha, so I guess the issue is outdated already.
