### ISSUE TITLE
2captcha dont solve recaptchaV2 on https://sepoliafaucet.com/

### ISSUE THREAD

**Issue by tera1oo4** [2captcha/2captcha-solver#59]
Trying solve captcha by API 2captcha and with extension, but have error: 
Extension: infinity loaded with "captcha solving" without result
API token: "recaptcha expected another token" ( try by callback and insert token in HTML iframe with "g-recaptcha-response"

**Comment by developer-vasily** [comment]
![Screenshot from 2023-07-17 08-45-01](https://github.com/2captcha/2captcha-solver/assets/114501229/6d704983-894c-44b8-b2c9-01eb9b28e797)
No problems found. Check your balance account.
