### ISSUE TITLE
[Firefox] Cannot login and post on reddit and pixiv if the extension is on.

### ISSUE THREAD

**Issue by famicom9x** [2captcha/2captcha-solver#62]
[Firefox] Cannot login and post on reddit and pixiv if the extension is on. Must disable the extension, turn off the extension isnt working.

**Comment by kratzky** [comment]
Does it work with Chrome?
Unfortunately Firefox version is outdated due to their weird Manifest V3 support.

**Comment by famicom9x** [comment]
> Does it work with Chrome? Unfortunately Firefox version is outdated due to their weird Manifest V3 support.

i dont know i dont use chrome and dont have plan to use it
