### ISSUE TITLE
Extension cannot detect Turnstile

### ISSUE THREAD

**Issue by udithobw** [2captcha/2captcha-solver#67]
I am trying to pass https://auth.1point3acres.com/ in selenium with extension. (I can successfully pass gcaptcha in selenium with 2captcha extension.)

When I use the [v3.3.4](https://github.com/2captcha/2captcha-solver/commit/21c68fdbed3d9fbdef049eaab49adb2b68855270), v3.3.3, [cloudflare-turnstile](https://github.com/2captcha/2captcha-solver/commit/4c645c97168a43e86e3c6cfc3f88cacac78cf92e), the extension cannot detect the captcha.

As I try [#58 ](https://github.com/2captcha/2captcha-solver/issues/58,) the extension can detect the captcha and shows successfully solved the captcha. However, when I submit it, the website still reminds me to solve captcha, indicating there is something wrong. 

Plus, I can successfully pass CF **directly in python scripts by 2captcha API** but fail in selenium with extension in  [#58 ](https://github.com/2captcha/2captcha-solver/issues/58,). 

After I review the commit of [#58 ](https://github.com/2captcha/2captcha-solver/issues/58,), I found it add data, pagedata, action, and etc. However, in my python scripts, I do not need to pass these parameters since this is an embedded captcha not a single page.

I have tried to remove these parameters in [content/captcha/turnstile/interceptor.js](https://github.com/2captcha/2captcha-solver/commit/36cbfe1986fd5d2f8b37043bb61fee398b63f8af#diff-e549113f92824d7459a9e1068c3d96e420f79d27615aee8487c9f393bd18bc5d), but it still not works properly.

**Comment by udithobw** [comment]
@kratzky I think 0% recognition might be caused by the wrong widgetId. In #58, @developer-vasily pass 
`                widgetId: params.sitekey,`

However, widgetId is something like 'zalv2', not the sitekey

I hope the above would be helpful

**Comment by developer-vasily** [comment]
![2023-09-07_10-05-28](https://github.com/2captcha/2captcha-solver/assets/114501229/af48ee4c-d7a9-4d1f-ab2a-765afd0d2f9c)

Please check again, it works
